import { defineStore } from "pinia";

export const useCyclistsStore = defineStore("cyclists", {
  state: () => ({
    // год рождения (сейчас сколько лет)
    // Страна, Нп.
    // results: [
    //   {
    //     season: 2022,
    //     distance: null,
    //     group: null,
    //     place: 1,
    //     number: 324,
    //     time: {},
    //     team: {},
    //     delay считать по группе
    //   },
    // ],
    cyclists: [
      {
        id: 1,
        name: "Борисов Алексей",
        birthdate: null,
        male: true,
        country: {
          name: "russia",
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 2,
        name: "Баранов Антон",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 3,
        name: "Сазонов Дмитрий",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 4,
        name: "Сумароков Владимир",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 5,
        name: "Спиридонов Юрий",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 6,
        name: "Лобанов Алексей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 7,
        name: "Дружинин Михаил",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 8,
        name: "Невзгодов Алексей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Турунтаево",
        results: [],
      },
      {
        id: 9,
        name: "Чирков Александр",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Кумора",
        results: [],
      },
      {
        id: 10,
        name: "Масличенко Александра",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 11,
        name: "Неводчиков Владимир",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 12,
        name: "Михалев Дмитрий",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 13,
        name: "Полоротов Сергей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 14,
        name: "Цыренов Сергей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 15,
        name: "Зубов Василий",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 16,
        name: "Буряков Максим",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 17,
        name: "Блинников Валентин",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Шенестуй",
        results: [],
      },
      {
        id: 18,
        name: "Толстопятов Евгений",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 19,
        name: "Денисов Евгений",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 20,
        name: "Тонтоев Вячеслав",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 21,
        name: "Конев Александр",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 22,
        name: "Анисимов Вячеслав",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 23,
        name: "Додонов Евгений",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 24,
        name: "Емельянов Сергей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 25,
        name: "Горохов Константин",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Ангарск",
        results: [],
      },
      {
        id: 26,
        name: "Скутин Андрей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 27,
        name: "Скороходов Владимир",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Ангарск",
        results: [],
      },
      {
        id: 28,
        name: "Алсаев Лев",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 29,
        name: "Рабданов Батор",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 30,
        name: "Афанасьева Анастасия",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 31,
        name: "Чойропова Анастасия",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 32,
        name: "Белоусова Нарана",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 33,
        name: "Гладышева Светлана",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Кяхта",
        results: [],
      },
      {
        id: 34,
        name: "Пешков Никита",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 35,
        name: "Дылгеров Доржи",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 36,
        name: "Спасов Тамир",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 37,
        name: "Волдочинский Александр",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 38,
        name: "Красиков Денис",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 39,
        name: "Хомяков Максим",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Новосибирск",
        results: [],
      },
      {
        id: 40,
        name: "Леонов Антон",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 41,
        name: "Павлов Евгений",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 42,
        name: "Орлов Максим",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 43,
        name: "Цыренов Олег",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 44,
        name: "Хмелёв Сергей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Турунтаево",
        results: [],
      },
      {
        id: 45,
        name: "Ляхов Вячеслав",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 46,
        name: "Головко Виктор",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 47,
        name: "Ефремов Юрий",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 48,
        name: "Гнездилов Дмитрий",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 49,
        name: "Теплоухов Сергей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Иркутск",
        results: [],
      },
      {
        id: 50,
        name: "Балданов Игорь",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Иркутск",
        results: [],
      },
      {
        id: 51,
        name: "Жамьянов Владимир",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Кяхта",
        results: [],
      },
      {
        id: 52,
        name: "Белоусов Вячеслав",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 53,
        name: "Буланов Вячеслав",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 54,
        name: "Санданов Денис",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 55,
        name: "Сидинкин Гермоген",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 56,
        name: "Сидинкин Иван",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 57,
        name: "Мищенко Владимир",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 58,
        name: "Суворов Владимир",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Турунтаево",
        results: [],
      },
      {
        id: 59,
        name: "Чайка Эдуард",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Иркутск",
        results: [],
      },
      {
        id: 60,
        name: "Вавко Руслан",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-удэ",
        results: [],
      },
      {
        id: 61,
        name: "Д.Туваанбат",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 62,
        name: "Козулина Анастасия",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 63,
        name: "Б.Номинжин",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 64,
        name: "Т.Биндэръяа",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 65,
        name: "Дубинин Александр",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 66,
        name: "Толстихин Стас",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 67,
        name: "С.Тэнгис",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 68,
        name: "Рабдаев Чингис",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 69,
        name: "Головко Максим",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 70,
        name: "С.Амин-Эрдэнэ",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 71,
        name: "Сафонова Вика",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 72,
        name: "Назимова Дарина",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 73,
        name: "Курышев Егор",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 74,
        name: "Л.Энхчулуун",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 75,
        name: "Стрекаловская Елизовета",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 76,
        name: "Б.Хишигжаргал",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 77,
        name: "Кудрявцева Наталия",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 78,
        name: "Стрекалова Диана",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 79,
        name: "Суворов Андрей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 80,
        name: "Оширова Эльвира",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 81,
        name: "Л.Алтансувд",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 82,
        name: "М.Нямлхагва",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 83,
        name: "П.Цэцэгмаа",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 84,
        name: "Гладышева Ольга",
        male: false,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 85,
        name: "Б.Отгонбаяр",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 86,
        name: "Брянский Валерий",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 87,
        name: "Болоков Денис",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Наушки",
        results: [],
      },
      {
        id: 88,
        name: "Агошков Алексей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 89,
        name: "Купцов Алексей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 90,
        name: "Попов Юрий",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 91,
        name: "Ободоев Мунхо",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 92,
        name: "Набиева Виктория",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 93,
        name: "Мумчинов Ермил",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 94,
        name: "Ионов Алексей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 95,
        name: "Вилюга Александр",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 96,
        name: "Махачкеев Жаргал",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 97,
        name: "Шишкин Денис",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 98,
        name: "Константинов Владимир",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 99,
        name: "Гыпылов Эрдэм",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 100,
        name: "Кох Иван",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 101,
        name: "Щукин Владимир",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 102,
        name: "Польских Сергей",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 103,
        name: "Будаев Жамсо",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 104,
        name: "Пушков Анатолий",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 105,
        name: "Кириллов Илья",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 106,
        name: "Дамбаев Жаргал",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 107,
        name: "Черкасов Александр",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 108,
        name: "Никитин Константин",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 109,
        name: "Левин Илья",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 110,
        name: "Петровский Александр",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 111,
        name: "Корнаков Денис",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 112,
        name: "Забанов Николай",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 113,
        name: "Бурков Иван",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 114,
        name: "Цыбикжапов Вячеслав",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 115,
        name: "Алексеева Ольга",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 116,
        name: "Гармаева Эржена",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 117,
        name: "Стрекаловская Елизавета",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 118,
        name: "Петроченко Туяна",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 119,
        name: "Мындускина Туяна",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 120,
        name: "Сергеева Анастасия",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 121,
        name: "Агошков Иван",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 122,
        name: "Малыгин К.",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 123,
        name: "Кашлаков Александр",
        male: true,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 124,
        name: "Казулина А.",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 125,
        name: "Польских Алина",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 126,
        name: "Новокрещенова Елена",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 127,
        name: "Цыренова Евгения",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 128,
        name: "Рыгзынова Хандама",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
      {
        id: 129,
        name: "Агошкова Юлия",
        male: false,
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "-",
        results: [],
      },
    ],
  }),
});
