import { defineStore } from "pinia";

export const useCyclistsStore = defineStore("cyclists", {
  state: () => ({
    // год рождения (сейчас сколько лет)
    // Страна, Нп.
    // results: [
    //   {
    //     season: 2022,
    //     distance: null,
    //     group: null,
    //     place: 1,
    //     number: 324,
    //     time: {},
    //     team: {},
    //     delay считать по группе
    //   },
    // ],
    cyclists: [
      {
        id: 1,
        name: "Борисов Алексей",
        birthdate: null,
        country: {
          name: "russia",
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 2,
        name: "Баранов Антон",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 3,
        name: "Сазонов Дмитрий",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 4,
        name: "Сумароков Владимир",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 5,
        name: "Спиридонов Юрий",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 6,
        name: "Лобанов Алексей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 7,
        name: "Дружинин Михаил",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 8,
        name: "Невзгодов Алексей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Турунтаево",
        results: [],
      },
      {
        id: 9,
        name: "Чирков Александр",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Кумора",
        results: [],
      },
      {
        id: 10,
        name: "Масличенко Александра",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 11,
        name: "Неводчиков Владимир",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 12,
        name: "Михалев Дмитрий",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 13,
        name: "Полоротов Сергей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 14,
        name: "Цыренов Сергей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 15,
        name: "Зубов Василий",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 16,
        name: "Буряков Максим",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 17,
        name: "Блинников Валентин",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Шенестуй",
        results: [],
      },
      {
        id: 18,
        name: "Толстопятов Евгений",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 19,
        name: "Денисов Евгений",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 20,
        name: "Тонтоев Вячеслав",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 21,
        name: "Конев Александр",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 22,
        name: "Анисимов Вячеслав",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 23,
        name: "Додонов Евгений",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 24,
        name: "Емельянов Сергей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 25,
        name: "Горохов Константин",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Ангарск",
        results: [],
      },
      {
        id: 26,
        name: "Скутин Андрей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Чита",
        results: [],
      },
      {
        id: 27,
        name: "Скороходов Владимир",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Ангарск",
        results: [],
      },
      {
        id: 28,
        name: "Алсаев Лев",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 29,
        name: "Рабданов Батор",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 30,
        name: "Афанасьева Анастасия",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 31,
        name: "Чойропова Анастасия",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 32,
        name: "Белоусова Нарана",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 33,
        name: "Гладышева Светлана",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Кяхта",
        results: [],
      },
      {
        id: 34,
        name: "Пешков Никита",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 35,
        name: "Дылгеров Доржи",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 36,
        name: "Спасов Тамир",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 37,
        name: "Волдочинский Александр",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 38,
        name: "Красиков Денис",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 39,
        name: "Хомяков Максим",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Новосибирск",
        results: [],
      },
      {
        id: 40,
        name: "Леонов Антон",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 41,
        name: "Павлов Евгений",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 42,
        name: "Орлов Максим",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 43,
        name: "Цыренов Олег",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 44,
        name: "Хмелёв Сергей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Турунтаево",
        results: [],
      },
      {
        id: 45,
        name: "Ляхов Вячеслав",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 46,
        name: "Головко Виктор",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 47,
        name: "Ефремов Юрий",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 48,
        name: "Гнездилов Дмитрий",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 49,
        name: "Теплоухов Сергей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Иркутск",
        results: [],
      },
      {
        id: 50,
        name: "Балданов Игорь",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Иркутск",
        results: [],
      },
      {
        id: 51,
        name: "Жамьянов Владимир",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Кяхта",
        results: [],
      },
      {
        id: 52,
        name: "Белоусов Вячеслав",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 53,
        name: "Буланов Вячеслав",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 54,
        name: "Санданов Денис",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 55,
        name: "Сидинкин Гермоген",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 56,
        name: "Сидинкин Иван",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 57,
        name: "Мищенко Владимир",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 58,
        name: "Суворов Владимир",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Турунтаево",
        results: [],
      },
      {
        id: 59,
        name: "Чайка Эдуард",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Иркутск",
        results: [],
      },
      {
        id: 60,
        name: "Вавко Руслан",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-удэ",
        results: [],
      },
      {
        id: 61,
        name: "Д.Туваанбат",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 62,
        name: "Козулина Анастасия",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 63,
        name: "Б.Номинжин",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 64,
        name: "Т.Биндэръяа",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 65,
        name: "Дубинин Александр",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 66,
        name: "Толстихин Стас",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 67,
        name: "С.Тэнгис",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 68,
        name: "Рабдаев Чингис",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 69,
        name: "Головко Максим",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 70,
        name: "С.Амин-Эрдэнэ",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 71,
        name: "Сафонова Вика",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 72,
        name: "Назимова Дарина",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 73,
        name: "Курышев Егор",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 74,
        name: "Л.Энхчулуун",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 75,
        name: "Стрекаловская Елизовета",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 76,
        name: "Б.Хишигжаргал",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 77,
        name: "Кудрявцева Наталия",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 78,
        name: "Стрекалова Диана",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 79,
        name: "Суворов Андрей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 80,
        name: "Оширова Эльвира",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 81,
        name: "Л.Алтансувд",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 82,
        name: "М.Нямлхагва",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 83,
        name: "П.Цэцэгмаа",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 84,
        name: "Гладышева Ольга",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 85,
        name: "Б.Отгонбаяр",
        birthdate: null,
        country: {
          name: null,
          title: "Монголия",
        },
        city: "-",
        results: [],
      },
      {
        id: 86,
        name: "Брянский Валерий",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
      {
        id: 87,
        name: "Болоков Денис",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Наушки",
        results: [],
      },
      {
        id: 88,
        name: "Агошков Алексей",
        birthdate: null,
        country: {
          name: null,
          title: "Россия",
        },
        city: "Улан-Удэ",
        results: [],
      },
    ],
  }),
});
