import { defineStore } from "pinia";

export const useMainStore = defineStore("main", {
  // state, getters, actions
  state: () => ({
    teams: [
      {
        id: 1,
        name: "GoRide",
      },
      {
        id: 2,
        name: "У-УАЗ",
      },
      {
        id: 3,
        name: "Велотяга",
      },
      {
        id: 4,
        name: "ТФОМС РБ",
      },
      {
        id: 5,
        name: "БРО Динамо",
      },
    ],
    marathons: {
      2022: [
        {
          distance: "260 км",
          type: "-",
          participants: [
            {
              place: 1,
              number: "324",
              name: "Борисов Алексей",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 18 и старше",
              time: "8:58:32",
              delay: "0",
            },
            {
              place: 2,
              number: "325",
              name: "Баранов Антон",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18 и старше",
              time: null, // сошёл
              delay: null,
            },
          ],
        },
        {
          distance: "200 км",
          type: "-",
          participants: [
            {
              place: 1,
              number: "213",
              name: "Сазонов Дмитрий",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18 и старше",
              time: "5:56:08",
              delay: null,
            },
            {
              place: 2,
              number: "208",
              name: "Сумароков Владимир",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 18 и старше",
              time: "6:05:28",
              delay: null,
            },
            {
              place: 3,
              number: "211",
              name: "Спиридонов Юрий",
              country: "Россия",
              city: "Улан-Удэ",
              team: 3,
              group: "М 18 и старше",
              time: "6:44:08",
              delay: null,
            },
            {
              place: 4,
              number: "214",
              name: "Лобанов Алексей",
              country: "Россия",
              city: "Улан-Удэ",
              team: 4,
              group: "М 18 и старше",
              time: "6:54:33",
              delay: null,
            },
            {
              place: 5,
              number: "200",
              name: "Дружинин Михаил",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18 и старше",
              time: "7:03:17",
              delay: null,
            },
            {
              place: 6,
              number: "216",
              name: "Невзгодов Алексей ",
              country: "Россия",
              city: "Турунтаево",
              team: null,
              group: "М 18 и старше",
              time: "7:33:46",
              delay: null,
            },
            {
              place: 7,
              number: "217",
              name: "Чирков Александр ",
              country: "Россия",
              city: "Кумора",
              team: null,
              group: "М 18 и старше",
              time: "7:41:40",
              delay: null,
            },
          ],
        },
        {
          distance: "100 км",
          type: "roadbike",
          participants: [
            {
              place: 1,
              number: "123",
              name: "Масличенко Александра",
              country: "Россия",
              city: "Улан-Удэ",
              team: 5,
              group: "Ж 18-40",
              time: "3:19:59",
              delay: null,
            },
            {
              place: 1,
              number: "110",
              name: "Неводчиков Владимир",
              country: "Россия",
              city: "Чита",
              team: null,
              group: "М 18-40",
              time: "2:26:04",
              delay: null,
            },
            {
              place: 2,
              number: "153",
              name: "Михалев Дмитрий",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-40",
              time: "2:29:55",
              delay: null,
            },
            {
              place: 3,
              number: "107",
              name: "Полоротов Сергей",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 18-40",
              time: "2:30:01",
              delay: null,
            },
            {
              place: 4,
              number: "111",
              name: "Цыренов Сергей",
              country: "Россия",
              city: "Улан-Удэ",
              team: null, // ФВС РБ
              group: "М 18-40",
              time: "2:30:19",
              delay: null,
            },
            {
              place: 5,
              number: "102",
              name: "Зубов Василий",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 18-40",
              time: "2:36:44",
              delay: null,
            },
            {
              place: 6,
              number: "198",
              name: "Буряков Максим",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-40",
              time: "2:38:30",
              delay: null,
            },
            {
              place: 7,
              number: "100",
              name: "Блинников Валентин",
              country: "Россия",
              city: "Шенестуй",
              team: null, // Пе-2
              group: "М 18-40",
              time: "3:08:43",
              delay: null,
            },
            {
              place: 8,
              number: "112",
              name: "Толстопятов Евгений",
              country: "Россия",
              city: "Чита",
              team: null,
              group: "М 18-40",
              time: "3:09:52",
              delay: null,
            },
            {
              place: 9,
              number: "109",
              name: "Денисов Евгений",
              country: "Россия",
              city: "Улан-Удэ",
              team: 3,
              group: "М 18-40",
              time: "3:14:02",
              delay: null,
            },
            {
              place: 10,
              number: "114",
              name: "Тонтоев Вячеслав",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-40",
              time: "3:47:20",
              delay: null,
            },
            {
              place: 11,
              number: "119",
              name: "Конев Александр",
              country: "Россия",
              city: "Улан-Удэ",
              team: 2,
              group: "М 18-40",
              time: "4:06:00",
              delay: null,
            },
          ],
        },
      ],
    },
  }),
});
