import { defineStore } from "pinia";

export const useMainStore = defineStore("main", {
  // state, getters, actions
  state: () => ({
    teams: [
      {
        id: 1,
        name: "GoRide",
      },
      {
        id: 2,
        name: "У-УАЗ",
      },
      {
        id: 3,
        name: "Велотяга",
      },
      {
        id: 4,
        name: "ТФОМС РБ",
      },
      {
        id: 5,
        name: "БРО Динамо",
      },
      {
        id: 6,
        name: "Веломания 03",
      },
    ],
    marathons: {
      2022: [
        {
          distance: "260 км",
          type: "-",
          participants: [
            {
              place: 1,
              number: "324",
              name: "Борисов Алексей",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 18 и старше",
              time: {
                hour: 8,
                minute: 58,
                sec: 32,
              },
              delay: null,
            },
            {
              place: null,
              number: "325",
              name: "Баранов Антон",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18 и старше",
              time: null, // сошёл
              delay: null,
            },
          ],
        },
        {
          distance: "200 км",
          type: "-",
          participants: [
            {
              place: 1,
              number: "213",
              name: "Сазонов Дмитрий",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18 и старше",
              time: {
                hour: 5,
                minute: 56,
                sec: 8,
              },
              delay: null,
            },
            {
              place: 2,
              number: "208",
              name: "Сумароков Владимир",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 18 и старше",
              time: {
                hour: 6,
                minute: 5,
                sec: 28,
              },
              delay: null,
            },
            {
              place: 3,
              number: "211",
              name: "Спиридонов Юрий",
              country: "Россия",
              city: "Улан-Удэ",
              team: 3,
              group: "М 18 и старше",
              time: {
                hour: 6,
                minute: 44,
                sec: 8,
              },
              delay: null,
            },
            {
              place: 4,
              number: "214",
              name: "Лобанов Алексей",
              country: "Россия",
              city: "Улан-Удэ",
              team: 4,
              group: "М 18 и старше",
              time: {
                hour: 6,
                minute: 54,
                sec: 33,
              },
              delay: null,
            },
            {
              place: 5,
              number: "200",
              name: "Дружинин Михаил",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18 и старше",
              time: {
                hour: 7,
                minute: 3,
                sec: 17,
              },
              delay: null,
            },
            {
              place: 6,
              number: "216",
              name: "Невзгодов Алексей ",
              country: "Россия",
              city: "Турунтаево",
              team: null,
              group: "М 18 и старше",
              time: {
                hour: 7,
                minute: 33,
                sec: 46,
              },
              delay: null,
            },
            {
              place: 7,
              number: "217",
              name: "Чирков Александр ",
              country: "Россия",
              city: "Кумора",
              team: null,
              group: "М 18 и старше",
              time: {
                hour: 7,
                minute: 41,
                sec: 40,
              },
              delay: null,
            },
          ],
        },
        {
          distance: "100 км",
          type: "roadbike",
          participants: [
            {
              place: 1,
              number: "123",
              name: "Масличенко Александра",
              country: "Россия",
              city: "Улан-Удэ",
              team: 5,
              group: "Ж 18-40",
              time: {
                hour: 3,
                minute: 19,
                sec: 59,
              },
              delay: null,
            },
            {
              place: 1,
              number: "110",
              name: "Неводчиков Владимир",
              country: "Россия",
              city: "Чита",
              team: null,
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 26,
                sec: 4,
              },
              delay: null,
            },
            {
              place: 2,
              number: "153",
              name: "Михалев Дмитрий",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 29,
                sec: 55,
              },
              delay: null,
            },
            {
              place: 3,
              number: "107",
              name: "Полоротов Сергей",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 30,
                sec: 1,
              },
              delay: null,
            },
            {
              place: 4,
              number: "111",
              name: "Цыренов Сергей",
              country: "Россия",
              city: "Улан-Удэ",
              team: null, // ФВС РБ
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 30,
                sec: 19,
              },
              delay: null,
            },
            {
              place: 5,
              number: "102",
              name: "Зубов Василий",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 36,
                sec: 44,
              },
              delay: null,
            },
            {
              place: 6,
              number: "198",
              name: "Буряков Максим",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 38,
                sec: 30,
              },
              delay: null,
            },
            {
              place: 7,
              number: "100",
              name: "Блинников Валентин",
              country: "Россия",
              city: "Шенестуй",
              team: null, // Пе-2
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 8,
                sec: 43,
              },
              delay: null,
            },
            {
              place: 8,
              number: "112",
              name: "Толстопятов Евгений",
              country: "Россия",
              city: "Чита",
              team: null,
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 9,
                sec: 52,
              },
              delay: null,
            },
            {
              place: 9,
              number: "109",
              name: "Денисов Евгений",
              country: "Россия",
              city: "Улан-Удэ",
              team: 3,
              group: "М 18-40",
              time: {
                hour: 3,
                minute: 14,
                sec: 2,
              },
              delay: null,
            },
            {
              place: 10,
              number: "114",
              name: "Тонтоев Вячеслав",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-40",
              time: {
                hour: 3,
                minute: 47,
                sec: 20,
              },
              delay: null,
            },
            {
              place: 11,
              number: "119",
              name: "Конев Александр",
              country: "Россия",
              city: "Улан-Удэ",
              team: 2,
              group: "М 18-40",
              time: {
                hour: 4,
                minute: 6,
                sec: 0,
              },
              delay: null,
            },
            {
              place: 1,
              number: "132",
              name: "Анисимов Вячеслав",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 41-50",
              time: {
                hour: 2,
                minute: 36,
                sec: 57,
              },
              delay: null,
            },
            {
              place: 2,
              number: "118",
              name: "Додонов Евгений",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 41-50",
              time: {
                hour: 2,
                minute: 41,
                sec: 13,
              },
              delay: null,
            },
            {
              place: 3,
              number: "134",
              name: "Емельянов Сергей",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 41-50",
              time: {
                hour: 2,
                minute: 41,
                sec: 20,
              },
              delay: null,
            },
            {
              place: 1,
              number: "185",
              name: "Горохов Константин",
              country: "Россия",
              city: "Ангарск",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 2,
                minute: 41,
                sec: 11,
              },
              delay: null,
            },
            {
              place: 2,
              number: "184",
              name: "Скутин Андрей",
              country: "Россия",
              city: "Чита",
              team: 1,
              group: "М 51 и старше",
              time: {
                hour: 2,
                minute: 41,
                sec: 19,
              },
              delay: null,
            },
            {
              place: 3,
              number: "186",
              name: "Скороходов Владимир",
              country: "Россия",
              city: "Ангарск",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 2,
                minute: 59,
                sec: 23,
              },
              delay: null,
            },
            {
              place: 4,
              number: "178",
              name: "Алсаев Лев",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 3,
                minute: 10,
                sec: 31,
              },
              delay: null,
            },
            {
              place: 5,
              number: "181",
              name: "Рабданов Батор",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 3,
                minute: 33,
                sec: 59,
              },
              delay: null,
            },
          ],
        },
        {
          distance: "100 км",
          type: "МТБ",
          participants: [
            {
              place: 1,
              number: "125",
              name: "Афанасьева Анастасия",
              country: "Россия",
              city: "Улан-Удэ",
              team: 6,
              group: "Ж 18-40",
              time: {
                hour: 4,
                minute: 8,
                sec: 20,
              },
              delay: null,
            },
            {
              place: 2,
              number: "138",
              name: "Чойропова Анастасия",
              country: "Россия",
              city: "Улан-Удэ",
              team: 6,
              group: "Ж 18-40",
              time: {
                hour: 4,
                minute: 19,
                sec: 11,
              },
              delay: null,
            },
            {
              place: 3,
              number: "141",
              name: "Белоусова Нарана",
              country: "Россия",
              city: "Улан-Удэ",
              team: null, // X-RIDE
              group: "Ж 18-40",
              time: {
                hour: 4,
                minute: 19,
                sec: 29,
              },
              delay: null,
            },
            {
              place: 4,
              number: "139",
              name: "Гладышева Светлана",
              country: "Россия",
              city: "Кяхта",
              team: null,
              group: "Ж 18-40",
              time: {
                hour: 4,
                minute: 38,
                sec: 52,
              },
              delay: null,
            },
            {
              place: 1,
              number: "149",
              name: "Пешков Никита",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-30",
              time: {
                hour: 3,
                minute: 34,
                sec: 44,
              },
              delay: null,
            },
            {
              place: 2,
              number: "156",
              name: "Дылгеров Доржи",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-30",
              time: {
                hour: 3,
                minute: 53,
                sec: 56,
              },
              delay: null,
            },
            {
              place: 3,
              number: "143",
              name: "Спасов Тамир",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-30",
              time: {
                hour: 3,
                minute: 57,
                sec: 14,
              },
              delay: null,
            },
            {
              place: 4,
              number: "161",
              name: "Волдочинский Александр",
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-30",
              time: {
                hour: 4,
                minute: 23,
                sec: 32,
              },
              delay: null,
            },
            // 31-50
            // 51 +
            
          ],
        },
      ],
    },
  }),
});
