import { defineStore } from "pinia";

export const useMainStore = defineStore("main", {
  // state, getters, actions
  state: () => ({
    teams: [
      {
        id: 1,
        name: "GoRide",
      },
      {
        id: 2,
        name: "У-УАЗ",
      },
      {
        id: 3,
        name: "Велотяга",
      },
      {
        id: 4,
        name: "ТФОМС РБ",
      },
      {
        id: 5,
        name: "БРО Динамо",
      },
      {
        id: 6,
        name: "Веломания 03",
      },
    ],
    marathons: {
      2022: [
        {
          distance: "260 км",
          type: "-",
          participants: [
            {
              place: 1,
              number: "324",
              name: "Борисов Алексей",
              id: 1,
              country: "Россия",
              city: "Чита",
              team: "GoRide",
              group: "М 18 и старше",
              time: {
                hour: 8,
                minute: 58,
                sec: 32,
              },
              delay: null,
            },
            {
              place: null,
              number: "325",
              name: "Баранов Антон",
              id: 2,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18 и старше",
              time: null, // сошёл
              delay: null,
            },
          ],
        },
        {
          distance: "200 км",
          type: "-",
          participants: [
            {
              place: 1,
              number: "213",
              name: "Сазонов Дмитрий",
              id: 3,
              country: "Россия",
              city: "Улан-Удэ",
              team: "У-УАЗ",
              group: "М 18 и старше",
              time: {
                hour: 5,
                minute: 56,
                sec: 8,
              },
              delay: null,
            },
            {
              place: 2,
              number: "208",
              name: "Сумароков Владимир",
              id: 4,
              country: "Россия",
              city: "Чита",
              team: "GoRide",
              group: "М 18 и старше",
              time: {
                hour: 6,
                minute: 5,
                sec: 28,
              },
              delay: null,
            },
            {
              place: 3,
              number: "211",
              name: "Спиридонов Юрий",
              id: 5,
              country: "Россия",
              city: "Улан-Удэ",
              team: "Велотяга",
              group: "М 18 и старше",
              time: {
                hour: 6,
                minute: 44,
                sec: 8,
              },
              delay: null,
            },
            {
              place: 4,
              number: "214",
              name: "Лобанов Алексей",
              id: 6,
              country: "Россия",
              city: "Улан-Удэ",
              team: "ТФОМС РБ",
              group: "М 18 и старше",
              time: {
                hour: 6,
                minute: 54,
                sec: 33,
              },
              delay: null,
            },
            {
              place: 5,
              number: "200",
              name: "Дружинин Михаил",
              id: 7,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18 и старше",
              time: {
                hour: 7,
                minute: 3,
                sec: 17,
              },
              delay: null,
            },
            {
              place: 6,
              number: "216",
              name: "Невзгодов Алексей",
              id: 8,
              country: "Россия",
              city: "Турунтаево",
              team: null,
              group: "М 18 и старше",
              time: {
                hour: 7,
                minute: 33,
                sec: 46,
              },
              delay: null,
            },
            {
              place: 7,
              number: "217",
              name: "Чирков Александр",
              id: 9,
              country: "Россия",
              city: "Кумора",
              team: null,
              group: "М 18 и старше",
              time: {
                hour: 7,
                minute: 41,
                sec: 40,
              },
              delay: null,
            },
          ],
        },
        {
          distance: "100 км",
          type: "roadbike",
          participants: [
            {
              place: 1,
              number: "123",
              name: "Масличенко Александра",
              id: 10,
              country: "Россия",
              city: "Улан-Удэ",
              team: "БРО Динамо",
              group: "Ж 18-40",
              time: {
                hour: 3,
                minute: 19,
                sec: 59,
              },
              delay: null,
            },
            {
              place: 1,
              number: "110",
              name: "Неводчиков Владимир",
              id: 11,
              country: "Россия",
              city: "Чита",
              team: null,
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 26,
                sec: 4,
              },
              delay: null,
            },
            {
              place: 2,
              number: "153",
              name: "Михалев Дмитрий",
              id: 12,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 29,
                sec: 55,
              },
              delay: null,
            },
            {
              place: 3,
              number: "107",
              name: "Полоротов Сергей",
              id: 13,
              country: "Россия",
              city: "Чита",
              team: "GoRide",
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 30,
                sec: 1,
              },
              delay: null,
            },
            {
              place: 4,
              number: "111",
              name: "Цыренов Сергей",
              id: 14,
              country: "Россия",
              city: "Улан-Удэ",
              team: "ФВС РБ",
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 30,
                sec: 19,
              },
              delay: null,
            },
            {
              place: 5,
              number: "102",
              name: "Зубов Василий",
              id: 15,
              country: "Россия",
              city: "Чита",
              team: "GoRide",
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 36,
                sec: 44,
              },
              delay: null,
            },
            {
              place: 6,
              number: "198",
              name: "Буряков Максим",
              id: 16,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-40",
              time: {
                hour: 2,
                minute: 38,
                sec: 30,
              },
              delay: null,
            },
            {
              place: 7,
              number: "100",
              name: "Блинников Валентин",
              id: 17,
              country: "Россия",
              city: "Шенестуй",
              team: "Пе-2", // Пе-2
              group: "М 18-40",
              time: {
                hour: 3,
                minute: 8,
                sec: 43,
              },
              delay: null,
            },
            {
              place: 8,
              number: "112",
              name: "Толстопятов Евгений",
              id: 18,
              country: "Россия",
              city: "Чита",
              team: null,
              group: "М 18-40",
              time: {
                hour: 3,
                minute: 9,
                sec: 52,
              },
              delay: null,
            },
            {
              place: 9,
              number: "109",
              name: "Денисов Евгений",
              id: 19,
              country: "Россия",
              city: "Улан-Удэ",
              team: "Велотяга",
              group: "М 18-40",
              time: {
                hour: 3,
                minute: 14,
                sec: 2,
              },
              delay: null,
            },
            {
              place: 10,
              number: "114",
              name: "Тонтоев Вячеслав",
              id: 20,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-40",
              time: {
                hour: 3,
                minute: 47,
                sec: 20,
              },
              delay: null,
            },
            {
              place: 11,
              number: "119",
              name: "Конев Александр",
              id: 21,
              country: "Россия",
              city: "Улан-Удэ",
              team: "У-УАЗ",
              group: "М 18-40",
              time: {
                hour: 4,
                minute: 6,
                sec: 0,
              },
              delay: null,
            },
            {
              place: 1,
              number: "132",
              name: "Анисимов Вячеслав",
              id: 22,
              country: "Россия",
              city: "Чита",
              team: "GoRide",
              group: "М 41-50",
              time: {
                hour: 2,
                minute: 36,
                sec: 57,
              },
              delay: null,
            },
            {
              place: 2,
              number: "118",
              name: "Додонов Евгений",
              id: 23,
              country: "Россия",
              city: "Чита",
              team: "GoRide",
              group: "М 41-50",
              time: {
                hour: 2,
                minute: 41,
                sec: 13,
              },
              delay: null,
            },
            {
              place: 3,
              number: "134",
              name: "Емельянов Сергей",
              id: 24,
              country: "Россия",
              city: "Улан-Удэ",
              team: "КЛЛ Соболь",
              group: "М 41-50",
              time: {
                hour: 2,
                minute: 41,
                sec: 20,
              },
              delay: null,
            },
            {
              place: 1,
              number: "185",
              name: "Горохов Константин",
              id: 25,
              country: "Россия",
              city: "Ангарск",
              team: "БайкалСпортТим",
              group: "М 51 и старше",
              time: {
                hour: 2,
                minute: 41,
                sec: 11,
              },
              delay: null,
            },
            {
              place: 2,
              number: "184",
              name: "Скутин Андрей",
              id: 26,
              country: "Россия",
              city: "Чита",
              team: "GoRide",
              group: "М 51 и старше",
              time: {
                hour: 2,
                minute: 41,
                sec: 19,
              },
              delay: null,
            },
            {
              place: 3,
              number: "186",
              name: "Скороходов Владимир",
              id: 27,
              country: "Россия",
              city: "Ангарск",
              team: "Пе-2",
              group: "М 51 и старше",
              time: {
                hour: 2,
                minute: 59,
                sec: 23,
              },
              delay: null,
            },
            {
              place: 4,
              number: "178",
              name: "Алсаев Лев",
              id: 28,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 3,
                minute: 10,
                sec: 31,
              },
              delay: null,
            },
            {
              place: 5,
              number: "181",
              name: "Рабданов Батор",
              id: 29,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 3,
                minute: 33,
                sec: 59,
              },
              delay: null,
            },
          ],
        },
        {
          distance: "100 км",
          type: "МТБ",
          participants: [
            {
              place: 1,
              number: "125",
              name: "Афанасьева Анастасия",
              id: 30,
              country: "Россия",
              city: "Улан-Удэ",
              team: "Веломания 03",
              group: "Ж 18-40",
              time: {
                hour: 4,
                minute: 8,
                sec: 20,
              },
              delay: null,
            },
            {
              place: 2,
              number: "138",
              name: "Чойропова Анастасия",
              id: 31,
              country: "Россия",
              city: "Улан-Удэ",
              team: 6,
              group: "Ж 18-40",
              time: {
                hour: 4,
                minute: 19,
                sec: 11,
              },
              delay: null,
            },
            {
              place: 3,
              number: "141",
              name: "Белоусова Нарана",
              id: 32,
              country: "Россия",
              city: "Улан-Удэ",
              team: "X-RIDE", // X-RIDE
              group: "Ж 18-40",
              time: {
                hour: 4,
                minute: 19,
                sec: 29,
              },
              delay: null,
            },
            {
              place: 4,
              number: "139",
              name: "Гладышева Светлана",
              id: 33,
              country: "Россия",
              city: "Кяхта",
              team: null,
              group: "Ж 18-40",
              time: {
                hour: 4,
                minute: 38,
                sec: 52,
              },
              delay: null,
            },
            {
              place: 1,
              number: "149",
              name: "Пешков Никита",
              id: 34,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-30",
              time: {
                hour: 3,
                minute: 34,
                sec: 44,
              },
              delay: null,
            },
            {
              place: 2,
              number: "156",
              name: "Дылгеров Доржи",
              id: 35,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-30",
              time: {
                hour: 3,
                minute: 53,
                sec: 56,
              },
              delay: null,
            },
            {
              place: 3,
              number: "143",
              name: "Спасов Тамир",
              id: 36,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-30",
              time: {
                hour: 3,
                minute: 57,
                sec: 14,
              },
              delay: null,
            },
            {
              place: 4,
              number: "161",
              name: "Волдочинский Александр",
              id: 37,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-30",
              time: {
                hour: 4,
                minute: 23,
                sec: 32,
              },
              delay: null,
            },
            // NEW NEW NEW
            {
              place: 1,
              number: "555",
              name: "Красиков Денис",
              id: 38,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 2,
                minute: 59,
                sec: 36,
              },
              delay: null,
            },
            {
              place: 2,
              number: "168",
              name: "Хомяков Максим",
              id: 39,
              country: "Россия",
              city: "Новосибирск",
              team: null,
              group: "М 31-50",
              time: {
                hour: 2,
                minute: 59,
                sec: 37,
              },
              delay: null,
            },
            {
              place: 3,
              number: "157",
              name: "Леонов Антон",
              id: 40,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 5,
                sec: 18,
              },
              delay: null,
            },
            {
              place: 4,
              number: "170",
              name: "Павлов Евгений",
              id: 41,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 7,
                sec: 49,
              },
              delay: null,
            },
            {
              place: 5,
              number: "192",
              name: "Орлов Максим",
              id: 42,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 9,
                sec: 27,
              },
              delay: null,
            },
            {
              place: 6,
              number: "165",
              name: "Цыренов Олег",
              id: 43,
              country: "Россия",
              city: "Улан-Удэ",
              team: "Веломания 03",
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 18,
                sec: 4,
              },
              delay: null,
            },
            {
              place: 7,
              number: "164",
              name: "Хмелёв Сергей",
              id: 44,
              country: "Россия",
              city: "Турунтаево",
              team: null,
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 23,
                sec: 36,
              },
              delay: null,
            },
            {
              place: 8,
              number: "155",
              name: "Ляхов Вячеслав",
              id: 45,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 28,
                sec: 7,
              },
              delay: null,
            },
            {
              place: 9,
              number: "135",
              name: "Головко Виктор",
              id: 46,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 28,
                sec: 26,
              },
              delay: null,
            },
            {
              place: 10,
              number: "169",
              name: "Ефремов Юрий",
              id: 47,
              country: "Россия",
              city: "Улан-Удэ",
              team: "Веломания 03",
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 33,
                sec: 29,
              },
              delay: null,
            },
            {
              place: 11,
              number: "137",
              name: "Гнездилов Дмитрий",
              id: 48,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 34,
                sec: 43,
              },
              delay: null,
            },
            {
              place: 12,
              number: "133",
              name: "Теплоухов Сергей",
              id: 49,
              country: "Россия",
              city: "Иркутск",
              team: null,
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 36,
                sec: 3,
              },
              delay: null,
            },
            {
              place: 13,
              number: "162",
              name: "Балданов Игорь",
              id: 50,
              country: "Россия",
              city: "Иркутск",
              team: null,
              group: "М 31-50",
              time: {
                hour: 3,
                minute: 50,
                sec: 12,
              },
              delay: null,
            },
            {
              place: 14,
              number: "171",
              name: "Жамьянов Владимир",
              id: 51,
              country: "Россия",
              city: "Кяхта",
              team: "Бурятская таможня",
              group: "М 31-50",
              time: {
                hour: 4,
                minute: 1,
                sec: 15,
              },
              delay: null,
            },
            {
              place: 15,
              number: "175",
              name: "Белоусов Вячеслав",
              id: 52,
              country: "Россия",
              city: "Улан-Удэ",
              team: "X-RIDE",
              group: "М 31-50",
              time: {
                hour: 4,
                minute: 19,
                sec: 29,
              },
              delay: null,
            },
            {
              place: 16,
              number: "173",
              name: "Буланов Вячеслав",
              id: 53,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 4,
                minute: 19,
                sec: 30,
              },
              delay: null,
            },
            {
              place: 17,
              number: "128",
              name: "Санданов Денис",
              id: 54,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 4,
                minute: 38,
                sec: 40,
              },
              delay: null,
            },
            {
              place: 18,
              number: "195",
              name: "Сидинкин Гермоген",
              id: 55,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 5,
                minute: 15,
                sec: 27,
              },
              delay: null,
            },
            {
              place: 19,
              number: "193",
              name: "Сидинкин Иван",
              id: 56,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 31-50",
              time: {
                hour: 5,
                minute: 32,
                sec: 13,
              },
              delay: null,
            },
            {
              place: 1,
              number: "177",
              name: "Мищенко Владимир",
              id: 57,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 2,
                minute: 56,
                sec: 42,
              },
              delay: null,
            },
            {
              place: 2,
              number: "180",
              name: "Суворов Владимир",
              id: 58,
              country: "Россия",
              city: "Турунтаево",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 3,
                minute: 31,
                sec: 14,
              },
              delay: null,
            },
            {
              place: 3,
              number: "188",
              name: "Чайка Эдуард",
              id: 59,
              country: "Россия",
              city: "Иркутск",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 3,
                minute: 36,
                sec: 39,
              },
              delay: null,
            },
            {
              place: 4,
              number: "163",
              name: "Вавко Руслан",
              id: 60,
              country: "Россия",
              city: "Улан-удэ",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 3,
                minute: 41,
                sec: 8,
              },
              delay: null,
            },
            {
              place: 5,
              number: "187",
              name: "Д.Туваанбат",
              id: 61,
              country: "Монголия",
              city: "-",
              team: null,
              group: "М 51 и старше",
              time: {
                hour: 4,
                minute: 24,
                sec: 5,
              },
              delay: null,
            },
          ],
        },
        {
          distance: "40 км",
          type: "-",
          participants: [
            {
              place: 1,
              number: "70",
              name: "Козулина Анастасия",
              id: 62,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "Ж 14-15",
              time: {
                hour: 1,
                minute: 31,
                sec: 52,
              },
              delay: null,
            },
            {
              place: 2,
              number: "56",
              name: "Б.Номинжин",
              id: 63,
              country: "Монголия",
              city: "-",
              team: null,
              group: "Ж 14-15",
              time: {
                hour: 1,
                minute: 41,
                sec: 32,
              },
              delay: null,
            },
            {
              place: 3,
              number: "53",
              name: "Т.Биндэръяа",
              id: 64,
              country: "Монголия",
              city: "-",
              team: null,
              group: "Ж 14-15",
              time: {
                hour: 1,
                minute: 54,
                sec: 45,
              },
              delay: null,
            },
            {
              place: 1,
              number: "23",
              name: "Дубинин Александр",
              id: 65,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 14-15",
              time: {
                hour: 1,
                minute: 19,
                sec: 37,
              },
              delay: null,
            },
            {
              place: 2,
              number: "73",
              name: "Толстихин Стас",
              id: 66,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 14-15",
              time: {
                hour: 1,
                minute: 31,
                sec: 13,
              },
              delay: null,
            },
            {
              place: 3,
              number: "45",
              name: "С.Тэнгис",
              id: 67,
              country: "Монголия",
              city: "-",
              team: null,
              group: "М 14-15",
              time: {
                hour: 1,
                minute: 36,
                sec: 6,
              },
              delay: null,
            },
            {
              place: 4,
              number: "51",
              name: "Рабдаев Чингис",
              id: 68,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 14-15",
              time: {
                hour: 1,
                minute: 41,
                sec: 31,
              },
              delay: null,
            },
            {
              place: 5,
              number: "44",
              name: "Головко Максим",
              id: 69,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 14-15",
              time: {
                hour: 1,
                minute: 42,
                sec: 37,
              },
              delay: null,
            },
            {
              place: null,
              number: "49",
              name: "С.Амин-Эрдэнэ",
              id: 70,
              country: "Монголия",
              city: "-",
              team: null,
              group: "М 14-15",
              time: null,
              delay: null,
            },
            {
              place: 1,
              number: "17",
              name: "Сафонова Вика",
              id: 71,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "Ж 16-17",
              time: {
                hour: 1,
                minute: 31,
                sec: 53,
              },
              delay: null,
            },
            {
              place: 2,
              number: "63",
              name: "Назимова Дарина",
              id: 72,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "Ж 16-17",
              time: {
                hour: 1,
                minute: 45,
                sec: 3,
              },
              delay: null,
            },
            {
              place: 1,
              number: "57",
              name: "Курышев Егор",
              id: 73,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 16-17",
              time: {
                hour: 1,
                minute: 19,
                sec: 24,
              },
              delay: null,
            },
            {
              place: 2,
              number: "61",
              name: "Л.Энхчулуун",
              id: 74,
              country: "Монголия",
              city: "-",
              team: null,
              group: "М 16-17",
              time: {
                hour: 1,
                minute: 27,
                sec: 22,
              },
              delay: null,
            },
            {
              place: 1,
              number: "24",
              name: "Стрекаловская Елизовета",
              id: 75,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "Ж 18-35",
              time: {
                hour: 1,
                minute: 40,
                sec: 33,
              },
              delay: null,
            },
            {
              place: 2,
              number: "22",
              name: "Б.Хишигжаргал",
              id: 76,
              country: "Монголия",
              city: "-",
              team: null,
              group: "Ж 18-35",
              time: {
                hour: 1,
                minute: 48,
                sec: 27,
              },
              delay: null,
            },
            {
              place: 3,
              number: "48",
              name: "Кудрявцева Наталия",
              id: 77,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "Ж 18-35",
              time: {
                hour: 1,
                minute: 50,
                sec: 44,
              },
              delay: null,
            },
            {
              place: 4,
              number: "21",
              name: "Стрекалова Диана",
              id: 78,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "Ж 18-35",
              time: {
                hour: 2,
                minute: 13,
                sec: 18,
              },
              delay: null,
            },
            {
              place: 1,
              number: "34",
              name: "Суворов Андрей",
              id: 79,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 18-35",
              time: {
                hour: 1,
                minute: 22,
                sec: 1,
              },
              delay: null,
            },
            {
              place: 1,
              number: "26",
              name: "Оширова Эльвира",
              id: 80,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "Ж 36 и старше",
              time: {
                hour: 1,
                minute: 43,
                sec: 27,
              },
              delay: null,
            },
            {
              place: 2,
              number: "29",
              name: "Л.Алтансувд",
              id: 81,
              country: "Монголия",
              city: "-",
              team: null,
              group: "Ж 36 и старше",
              time: {
                hour: 1,
                minute: 56,
                sec: 16,
              },
              delay: null,
            },
            {
              place: 3,
              number: "28",
              name: "М.Нямлхагва",
              id: 82,
              country: "Монголия",
              city: "-",
              team: null,
              group: "Ж 36 и старше",
              time: {
                hour: 1,
                minute: 56,
                sec: 38,
              },
              delay: null,
            },
            {
              place: 4,
              number: "30",
              name: "П.Цэцэгмаа",
              id: 83,
              country: "Монголия",
              city: "-",
              team: null,
              group: "Ж 36 и старше",
              time: {
                hour: 2,
                minute: 2,
                sec: 46,
              },
              delay: null,
            },
            {
              place: 5,
              number: "25",
              name: "Гладышева Ольга",
              id: 84,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "Ж 36 и старше",
              time: {
                hour: 2,
                minute: 4,
                sec: 23,
              },
              delay: null,
            },
            {
              place: 1,
              number: "42",
              name: "Б.Отгонбаяр",
              id: 85,
              country: "Монголия",
              city: "-",
              team: null,
              group: "М 36 и старше",
              time: {
                hour: 1,
                minute: 26,
                sec: 4,
              },
              delay: null,
            },
            {
              place: 2,
              number: "38",
              name: "Брянский Валерий",
              id: 86,
              country: "Россия",
              city: "Улан-Удэ",
              team: "Велотяга",
              group: "М 36 и старше",
              time: {
                hour: 1,
                minute: 29,
                sec: 43,
              },
              delay: null,
            },
            {
              place: 3,
              number: "41",
              name: "Болоков Денис",
              id: 87,
              country: "Россия",
              city: "Наушки",
              team: "Бурятская таможня",
              group: "М 36 и старше",
              time: {
                hour: 1,
                minute: 43,
                sec: 23,
              },
              delay: null,
            },
            {
              place: 4,
              number: "39",
              name: "Агошков Алексей",
              id: 88,
              country: "Россия",
              city: "Улан-Удэ",
              team: null,
              group: "М 36 и старше",
              time: {
                hour: 1,
                minute: 53,
                sec: 12,
              },
              delay: null,
            },
          ],
        },
      ],
    },
  }),
});
